'use strict';
const $=id=>document.getElementById(id),f=(n,p=2)=>Number.isFinite(n)?n.toLocaleString('en-US',{minimumFractionDigits:p,maximumFractionDigits:p}):n===Infinity?'∞':'—';
const specs={geometry:[['d','斷面深度 d','cm',40,'H／箱型之外側總深度；圓管為外徑 D。'],['b','翼板／箱型寬 b','cm',40,'外側總寬度；箱型寬厚比會扣除兩侧板厚。'],['tw','腹板厚 tw','cm',1.3,'H 型腹板實際厚度。'],['tf','翼板厚 tf','cm',2.1,'H 型翼板厚；箱型與圓管為等厚板厚 t。']],material:[['Fy','降伏強度 Fy','kgf/cm²',2400,'依鋼種、板厚及材料證明輸入，非所有鋼材一律使用預設值。'],['E','彈性模數 E','kgf/cm²',2040000,'規範第 1.6 節：2,040,000 kgf/cm²。'],['G','剪力模數 G','kgf/cm²',810000,'規範第 1.6 節：810,000 kgf/cm²；H 柱純扭轉挫屈使用。']],lengths:[['Lx','X 軸無支撐長 Lx','cm',465,'繞 X 軸挫屈的無支撐長度，非翼板側撐長 Lb。'],['Kx','有效長度係數 Kx','無因次',1,'由構架穩定性分析決定；兩端理想鉸接可取 1。'],['Ly','Y 軸無支撐長 Ly','cm',465,'繞 Y 軸挫屈的無支撐長度。'],['Ky','有效長度係數 Ky','無因次',1,'依 Y 軸彎曲平面的端部束制及側移條件決定。'],['Lb','翼板側撐間距 Lb','cm',465,'H 柱強軸側向扭轉挫屈；箱型柱提高容許彎應力的側撐限制。'],['Lz','扭轉無支撐長 Lz','cm',465,'H 柱防止扭轉之支撐間距，與一般側向支撐不必然相同。'],['Kz','扭轉有效長係數 Kz','無因次',1,'依翹曲與扭轉束制決定；未知時不可任意縮小。']],loads:[['N','軸壓力 N','tf',100,'壓力為正。請輸入已選定 ASD 載重組合之構材內力。'],['Mx','X 軸彎矩 Mx','tf·m',10,'繞斷面 X 軸的彎矩，通常為 H 型強軸；取絕對值。'],['My','Y 軸彎矩 My','tf·m',2,'繞斷面 Y 軸的彎矩，通常為 H 型弱軸；取絕對值。']],coeffs:[['Cmx','X 軸修正係數 Cm','0.2–1.0',1,'預設 1.0；依第 8.2 節端彎矩梯度、側移與橫載情況設定。'],['Cmy','Y 軸修正係數 Cm','0.2–1.0',1,'預設 1.0；依第 8.2 節決定。']]};
for(const [group,fields] of Object.entries(specs))$(group).innerHTML=fields.map(([id,label,unit,value,tip])=>`<label id="wrap-${id}" title="${tip}"><span id="label-${id}">${label}</span><span class="label-unit">${unit}</span><input id="${id}" type="number" step="any" value="${value}" aria-label="${label}，${unit}" title="${tip}" ${['Mx','My'].includes(id)?'':'min="0"'}></label>`).join('');
function values(){const v={shape:$('shape').value,fabrication:$('fabrication').value,weld:$('weld').value};Object.values(specs).flat().forEach(([id])=>v[id]=$(id).value===''?NaN:Number($(id).value));return v;}
let current;
function presetNote(){
 const kind=$('shape').value,selected=SECTION_PRESETS[kind].find(p=>p.id===$('section-preset').value);
 $('preset-note').textContent=selected?(kind==='BOX'?'已載入設計預設尺寸；非廠商庫存規格。':kind==='PIPE'?'已載入美亞型錄外徑與板厚；鋼種、Fy 與結構用途適用性須另行確認。':'已載入東和 H 型鋼標稱尺寸，不含型錄圓角性質。')+'尺寸可修改；材料、長度與載重維持原設定。':('自訂尺寸，可直接修改下方欄位。'+(kind==='H'?' A、I、S 採直角板件幾何計算，不含型鋼圓角。':''));
}
function syncPresetList(){
 const list=SECTION_PRESETS[$('shape').value],groups=[...new Set(list.map(p=>p.group))];
 $('section-preset').innerHTML='<option value="custom">自訂尺寸</option>'+groups.map(g=>`<optgroup label="${g}">${list.filter(p=>p.group===g).map(p=>`<option value="${p.id}">${p.label} mm</option>`).join('')}</optgroup>`).join('');
 const keys=$('shape').value==='PIPE'?['d','tf']:$('shape').value==='BOX'?['d','b','tf']:['d','b','tw','tf'];
 const match=list.find(p=>keys.every(k=>Math.abs(Number($(k).value)-p[k])<1e-9));
 $('section-preset').value=match&&($('shape').value!=='H'||$('fabrication').value==='rolled')?match.id:'custom';presetNote();
}
function applyPreset(){
 const p=SECTION_PRESETS[$('shape').value].find(p=>p.id===$('section-preset').value);
 if(p){for(const k of ['d','b','tw','tf'])$(k).value=p[k];if($('shape').value==='H')$('fabrication').value='rolled';}
 presetNote();render();
}

function updateShape(reset=false){const shape=$('shape').value;$('fabrication-wrap').hidden=shape!=='H';$('weld-wrap').hidden=shape!=='BOX';for(const id of ['tw','Lz','Kz','G'])$('wrap-'+id).hidden=shape!=='H';$('wrap-b').hidden=shape==='PIPE';$('wrap-Lb').hidden=shape==='PIPE';$('label-d').textContent=shape==='PIPE'?'圓管外徑 D':'斷面深度 d';$('label-tf').textContent=shape==='H'?'翼板厚 tf':'板厚 t';if(reset){if(shape==='BOX'){$('d').value=40;$('b').value=40;$('tf').value=1.6;}if(shape==='PIPE'){$('d').value=40.64;$('tf').value=1.27;}if(shape==='H')for(const k of ['d','b','tw','tf'])$(k).value=defaults[k];}syncPresetList();render();}
const pill=(ratio,valid=true)=>!valid?'<span class="pill pending">待分析</span>':ratio<=1+1e-9?'<span class="pill">通過</span>':'<span class="pill fail">未通過</span>';
const row=(name,demand,capacity,ratio,valid=true)=>`<tr><td>${name}</td><td>${demand}</td><td>${valid?capacity:'—'}</td><td>${valid?f(ratio,3):'—'}</td><td>${pill(ratio,valid)}</td></tr>`;
const det=(title,body,open=false)=>`<details ${open?'open':''}><summary>${title}</summary>${body}</details>`;
const formula=s=>`<div class="formula">${s}</div>`;
function render(){
 const hadDetails=$('calculations').querySelectorAll('details').length>0;
 const expanded=new Set([...$('calculations').querySelectorAll('details[open] summary')].map(e=>e.textContent));
 const r=compute(values());current=r;const error=$('error');error.hidden=!r.errors.length;$('results').hidden=!!r.errors.length;if(r.errors.length){$('mobile-result').textContent='請檢查輸入參數';error.textContent=r.errors.join('；');return;}
 const v=r.v,valid=r.valid;$('status').textContent={pass:'已實作項目通過',fail:'未通過檢核',pending:'需另行分析'}[r.status];$('status-note').textContent=!valid?'斷面超出適用範圍，停止容量判定。':r.slim>200?'長細比超過建議值，需調整支承或斷面。':r.ratio>1?'需求超過容許值，請調整斷面、支承或載重。':'單一載重組合 · '+r.control+'控制軸壓容量';document.querySelector('.summary').className='summary '+r.status;$('mobile-result').textContent=$('status').textContent+' · '+(valid?f(r.ratio,3):'待分析');$('ratio').textContent=valid?f(r.ratio,3):'—';$('meter').style.width=valid?Math.min(r.ratio*100,100)+'%':'0';
 $('metrics').innerHTML=`<div class="metric"><span>容許純軸壓力 Pa</span><strong>${r.axialCapacityValid?f(r.Pa,1):'—'} <small>tf</small></strong><p>${r.axialCapacityValid?"Fa × A；不含彎矩折減":"純軸壓寬厚比超限"}</p></div><div class="metric"><span>最大彎曲長細比</span><strong>${f(r.slim,2)}</strong><p>控制：${r.lx>=r.ly?'X':'Y'} 軸 · 建議 ≤ 200</p></div><div class="metric"><span>斷面積 A</span><strong>${f(r.A,2)} <small>cm²</small></strong><p>理論幾何 · 不計圓角</p></div>`;
 let rows=r.local.map(l=>row(l.name,f(l.value),f(l.cap),l.ratio));rows.push(row('彎曲長細比 KL/r',f(r.slim),'200（建議）',r.slim/200));rows.push(row('軸壓應力 fa',f(r.fa),f(r.Fa)+' kgf/cm²',r.axial,valid),row('X 軸彎曲 fbx',f(r.fbxReq),f(r.fbx)+' kgf/cm²',r.bx,valid),row('Y 軸彎曲 fby',f(r.fbyReq),f(r.fby)+' kgf/cm²',r.by,valid));if(r.axial<=.15)rows.push(row('軸彎互制 8.2-3',valid?f(r.simple,3):'—','1.000',r.simple,valid));else rows.push(row('穩定互制 8.2-1',valid?f(r.amplified,3):'—','1.000',r.amplified,valid),row('降伏互制 8.2-2',valid?f(r.yieldInteraction,3):'—','1.000',r.yieldInteraction,valid));$('checks').innerHTML=rows.join('');$('warnings').innerHTML=[...r.blocks,...r.warnings].map(w=>`<div class="warning">${w}</div>`).join('');
 let geom=v.shape==='H'?'A = 2btf + (d−2tf)tw<br>Ix = [bd³−(b−tw)(d−2tf)³]/12<br>Iy = [2tf·b³+(d−2tf)tw³]/12':v.shape==='BOX'?'A = bd−(b−2t)(d−2t)<br>Ix = [bd³−(b−2t)(d−2t)³]/12<br>Iy = [db³−(d−2t)(b−2t)³]/12':'A = π[D²−(D−2t)²]/4<br>Ix = Iy = π[D⁴−(D−2t)⁴]/64';
 let parts=[det('01　斷面性質與單位轉換',formula(geom+`<br>A = ${f(r.A)} cm²<br>Ix = ${f(r.Ix)} cm⁴；Iy = ${f(r.Iy)} cm⁴<br>Sx = Ix/(d/2) = ${f(r.Sx)} cm³<br>Sy = Iy/(b/2) = ${f(r.Sy)} cm³<br>rx = √(Ix/A) = ${f(r.rx,3)} cm<br>ry = √(Iy/A) = ${f(r.ry,3)} cm`)+`<p>1 tf＝1,000 kgf；1 tf·m＝100,000 kgf·cm。常數含 Fy 的經驗公式使用 Fy＝${f(v.Fy/1000,3)} tf/cm²。</p>`,true),det('02　寬厚比與適用性',formula(r.local.map(l=>`${l.name} = ${f(l.value,3)}；上限 = ${f(l.cap,3)}（${l.ref}）`).join('<br>')+`<br>kc = ${f(r.kc,4)}`)+`<p>H 型翼板 λr＝25√(kc/Fy)；H 型受壓腹板採 68/√Fy。箱型板件 λr＝63/√Fy；圓管軸壓 λr＝232/Fy、純彎曲 λr＝630/Fy。此處 Fy 單位 tf/cm²。</p>`)];
 if(valid){const faformula=v.shape==='BOX'?'λ ≤ Cc：Fa = 0.6Fy[0.6(λ/Cc)³−1.14(λ/Cc)²−0.085(λ/Cc)+1]<br>λ > Cc：Fa = 0.45π²E/λ²（6.7-1／6.7-2）':'λ < Cc：Fa = [1−λ²/(2Cc²)]Fy / [5/3+3λ/(8Cc)−λ³/(8Cc³)]<br>λ ≥ Cc：Fa = 12π²E/(23λ²)（6.3-1／6.3-2）';parts.push(det('03　雙軸挫屈與容許軸壓',formula(`λx = KxLx/rx = ${f(v.Kx)}×${f(v.Lx)}/${f(r.rx,3)} = ${f(r.lx,3)}<br>λy = KyLy/ry = ${f(v.Ky)}×${f(v.Ly)}/${f(r.ry,3)} = ${f(r.ly,3)}<br>Cc = √(2π²E/Fy) = ${f(r.Cc,3)}<br>${faformula}<br>Fax = ${f(r.Fax)}；Fay = ${f(r.Fay)} kgf/cm²`)+(v.shape==='H'?formula(`H 型雙對稱扭轉挫屈（6.4 解說引用極限設計法附錄 2）<br>J ≈ [2btf³+htw³]/3 = ${f(r.J,3)} cm⁴<br>Cw ≈ tf·b³(d−tf)²/24 = ${f(r.Cw)} cm⁶<br>Fez = [π²E·Cw/(KzLz)²+GJ]/(Ix+Iy) = ${f(r.Fez)} kgf/cm²<br>λz,eq = π√(E/Fez) = ${f(r.lz,3)}<br>Faz = ${f(r.Faz)} kgf/cm²（代入 6.3 曲線）`):'')+formula(`Fa = min(Fax, Fay${v.shape==='H'?', Faz':''}) = ${f(r.Fa)} kgf/cm²<br>${r.axialCapacityValid?"Pa = Fa×A/1000 = "+f(r.Pa,3)+" tf":"純軸壓寬厚比超限：不提供純軸壓容量 Pa"}<br>fa = N×1000/A = ${f(v.N)}×1000/${f(r.A)} = ${f(r.fa)} kgf/cm²`)));
 let bend=v.shape==='H'?`Lc = min[20b/√Fy, 1400Af/(dFy)] = ${f(r.Lcx)} cm<br>Lb = ${f(v.Lb)} cm；Cb = 1.0<br>rT = √[(tf·b³/12+(h/6)tw³/12)/(btf+htw/6)] = ${f(r.rT,3)} cm<br>Lb/rT = ${f(v.Lb/r.rT,3)}<br>短側撐、結實：Fbx＝0.66Fy<br>半結實翼板：Fbx＝Fy[0.79−0.0075·b/(2tf)√(Fy/kc)]<br>長側撐：取 7.2-6／7.2-7 與 7.2-8 較大值，≤0.6Fy 並受局部彎曲上限控制<br>7.2-6：Fb＝[2/3−Fy(Lb/rT)²/107600]Fy<br>7.2-7：Fb＝12000/(Lb/rT)²<br>7.2-8：Fb＝840Af/(Lb·d)<br>弱軸結實：Fby＝0.75Fy；半結實依 7.3-2／7.3-3`:v.shape==='BOX'?`Lc,x = 84b/Fy = ${f(r.Lcx)} cm<br>Lc,y = 84d/Fy = ${f(r.Lcy)} cm<br>滿足結實、幾何與側撐限制：Fb＝0.66Fy；否則本版保守採 0.6Fy`:'D/t ≤ 145/Fy：Fb＝0.66Fy；半結實：Fb＝0.60Fy（此處 Fy 單位 tf/cm²）';
 parts.push(det('04　雙軸容許彎應力',formula(bend)+formula(`Fbx = ${f(r.fbx)} kgf/cm²（${r.bendingX}）<br>Fby = ${f(r.fby)} kgf/cm²（${r.bendingY}）<br>fbx = |Mx|×100000/Sx = ${f(r.fbxReq)} kgf/cm²<br>fby = |My|×100000/Sy = ${f(r.fbyReq)} kgf/cm²`)+`<p>上述含 20、1400、107600、12000、840、84 等常數的公式使用 cm 與 tf/cm²，計算後轉為 kgf/cm²。</p>`));parts.push(det('05　軸力與彎矩共同作用',formula(`fa/Fa = ${f(r.axial,4)} ${r.axial<=.15?'≤':'>'} 0.15<br>F′ex = 12π²E/[23(KxLx/rx)²] = ${f(r.Fex)} kgf/cm²<br>F′ey = 12π²E/[23(KyLy/ry)²] = ${f(r.Fey)} kgf/cm²<br>1−fa/F′ex = ${f(r.dx,4)}；1−fa/F′ey = ${f(r.dy,4)}`)+formula(r.axial<=.15?`8.2-3：fa/Fa + fbx/Fbx + fby/Fby<br>= ${f(r.axial,4)} + ${f(r.bx,4)} + ${f(r.by,4)} = ${f(r.simple,4)} ≤ 1.0`:`8.2-1：fa/Fa + Cmx·fbx/[(1−fa/F′ex)Fbx] + Cmy·fby/[(1−fa/F′ey)Fby]<br>= ${f(r.amplified,4)} ≤ 1.0<br>8.2-2：fa/(0.6Fy) + fbx/Fbx + fby/Fby<br>= ${f(r.yieldInteraction,4)} ≤ 1.0`)+`<p>整體判定同時要求軸壓、各軸彎曲、適用互制式及長細比檢查符合。零彎矩項取零，避免零除非正分母；非零彎矩遇分母 ≤ 0 時判未通過。</p>`));}
 else parts.push('<p class="warning">容量與互制計算已暫停，請先處理上方適用範圍提示。</p>');$('calculations').innerHTML=parts.join('');for(const el of $('calculations').querySelectorAll('details'))if(hadDetails)el.open=expanded.has(el.querySelector('summary').textContent);draw(r);
}
function draw(r){const v=r.v,d=v.d,b=v.b,sc=Math.min(190/b,170/d),w=b*sc,hh=d*sc,tx=170-w/2,ty=130-hh/2,tf=v.tf*sc,tw=v.tw*sc;const line=(x1,y1,x2,y2,extra='')=>`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="#6c869c" ${extra}/>`;const text=(x,y,t)=>`<text x="${x}" y="${y}" text-anchor="middle">${t}</text>`;const rect=(x,y,w,h)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="#315678" stroke="#173d61"/>`;let shape=v.shape==='H'?rect(tx,ty,w,tf)+rect(170-tw/2,ty+tf,tw,hh-2*tf)+rect(tx,ty+hh-tf,w,tf):v.shape==='BOX'?`<path d="M${tx},${ty}h${w}v${hh}h-${w}z M${tx+tw},${ty+tf}v${hh-2*tf}h${w-2*tw}v-${hh-2*tf}z" fill="#315678" fill-rule="evenodd" stroke="#173d61"/>`:`<circle cx="170" cy="130" r="${w/2-tf/2}" fill="none" stroke="#315678" stroke-width="${tf}"/>`;
 $('section-svg').innerHTML=shape+line(tx,ty-13,tx+w,ty-13)+line(tx,ty-18,tx,ty-8)+line(tx+w,ty-18,tx+w,ty-8)+text(170,ty-22,`${v.shape==='PIPE'?'D':'b'}＝${f(b)} cm`)+line(tx+w+20,ty,tx+w+20,ty+hh)+line(tx+w+15,ty,tx+w+25,ty)+line(tx+w+15,ty+hh,tx+w+25,ty+hh)+`<text transform="translate(${tx+w+35},130) rotate(90)" text-anchor="middle">${v.shape==='PIPE'?'D':'d'}＝${f(d)} cm</text>`+line(35,130,300,130,'stroke-dasharray="5 4"')+line(170,30,170,225,'stroke-dasharray="5 4"')+text(302,122,'x')+text(181,230,'y')+text(170,253,v.shape==='H'?`tf＝${f(v.tf)} cm　tw＝${f(v.tw)} cm`:`t＝${f(v.tf)} cm`);
 $('column-svg').innerHTML=`<defs><marker id="arrow" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6" fill="#007f76"/></marker></defs>`+rect(115,60,16,145)+line(75,60,150,60)+line(75,205,150,205)+line(123,22,123,54,'stroke-width="2" marker-end="url(#arrow)"')+text(171,34,`N＝${f(v.N,1)} tf`)+line(220,60,220,205)+line(214,60,226,60)+line(214,205,226,205)+text(248,118,`Lx ${f(v.Lx,0)}`)+text(248,140,`Ly ${f(v.Ly,0)}`)+text(248,163,'cm')+text(148,235,`Kx＝${f(v.Kx)}　Ky＝${f(v.Ky)}`)+text(148,258,`Mx ${f(v.Mx,1)} / My ${f(v.My,1)} tf·m`);
 $('section-name').textContent=v.shape==='H'?`H ${f(d*10,0)} × ${f(b*10,0)} × ${f(v.tw*10,1)} × ${f(v.tf*10,1)} mm`:v.shape==='BOX'?`BOX ${f(d*10,0)} × ${f(b*10,0)} × ${f(v.tf*10,1)} mm`:`PIPE Ø${f(d*10,1)} × ${f(v.tf*10,1)} mm`;
}
$('inputs').addEventListener('submit',e=>e.preventDefault());$('inputs').addEventListener('input',e=>{if(['shape','section-preset'].includes(e.target.id))return;if(['d','b','tw','tf','fabrication'].includes(e.target.id)){$('section-preset').value='custom';presetNote();}render();});$('section-preset').addEventListener('change',applyPreset);$('shape').addEventListener('change',()=>updateShape(true));$('fabrication').addEventListener('change',render);$('weld').addEventListener('change',render);$('reset').addEventListener('click',()=>{Object.entries(defaults).forEach(([k,v])=>{if($(k))$(k).value=v;});updateShape();});updateShape();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_steel_column_check',description:'讀取本頁目前鋼柱輸入、檢核狀態及控制比值。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({inputs:values(),errors:current.errors,status:current.status,ratio:current.valid&&Number.isFinite(current.ratio)?current.ratio:null,warnings:current.warnings,limitations:current.blocks})})).catch(()=>{});}catch{}}
