'use strict';
const ColumnTrace=(()=>{
 const show=x=>typeof x==='number'?Number.isFinite(x)?String(x):x===Infinity?'∞':'−∞':typeof x==='object'?JSON.stringify(x,(_,v)=>typeof v==='number'&&!Number.isFinite(v)?String(v):v):String(x);
 const lines=t=>[t.formula,'本次代入：'+Object.entries(t.operands).map(([k,v])=>k+'='+show(v)).join('；'),'實際結果：'+show(t.result)+' '+t.unit,t.condition].filter(Boolean);
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function html(r){return '<details><summary>06　同引擎完整計算紀錄</summary>'+r.trace.map(t=>'<h3>'+esc(t.title)+'</h3><div class="formula">'+lines(t).map(esc).join('<br>')+'</div>').join('')+'</details>';}
 function diagram(){const a=document.getElementById('section-svg'),b=document.getElementById('column-svg');return '<svg xmlns="http://www.w3.org/2000/svg" width="680" height="290" viewBox="0 0 680 290"><style>text{font:12px Arial,sans-serif;fill:#173d61} .dim{stroke:#536e87;fill:none} .shape{fill:#cde7e5;stroke:#173d61;stroke-width:2}</style><svg x="0" width="340" height="270" viewBox="0 0 340 270">'+a.innerHTML+'</svg><svg x="340" width="340" height="270" viewBox="0 0 340 270">'+b.innerHTML+'</svg></svg>';}
 async function build(m){const snapshot=structuredClone(m);if(!snapshot.trace?.length)throw new Error('無有效本次計算');const report={title:'鋼柱構件計算報告書',valid:true,summary:[snapshot.project,snapshot.member,snapshot.author,snapshot.time,snapshot.status,snapshot.note,snapshot.section,snapshot.preset].join('；'),inputs:snapshot.inputs.map(([label,value,unit])=>({label,value,unit})),steps:snapshot.trace.map(t=>({title:t.title,formula:t.formula,substitution:Object.entries(t.operands).map(([k,v])=>k+'='+show(v)).join('；'),result:show(t.result),unit:t.unit,condition:t.condition})).concat(snapshot.calculations.map(p=>({title:p.title,formula:p.lines.join('\n'),result:''}))),tables:[{title:'逐項檢核結果',headers:['項目','計算值','容許值','比值','結果'],rows:snapshot.checks},{title:'本次斷面預設資料表',headers:['原表列','尺寸名稱','d (mm)','b (mm)','tw (mm)','tf (mm)'],rows:snapshot.presetRows,source:snapshot.presetSource,note:'尺寸 mm÷10→cm；僅載入幾何，不載入型錄圓角斷面性質。無內插、無斷面搜尋。自訂尺寸使用本次輸入。'}],diagram:{svg:snapshot.diagram,width:680,height:290,caption:'本次斷面、無支承長度與載重；依同次輸入繪製。'},conclusions:[snapshot.status,snapshot.note,'需求容量比：'+snapshot.ratio,...snapshot.warnings,...snapshot.basis,...snapshot.sources,'計算全精度；顯示值四捨五入。']};return await CalculationDocx.build(report);}
 return {html,diagram,build,lines};
})();

