const assert=require('node:assert/strict');
const {compute,defaults,allowable}=require('../engine.js');
let count=0;const check=(name,fn)=>{fn();count++;console.log('PASS',name)};const near=(a,b,t=1e-6)=>assert.ok(Math.abs(a-b)<=t,`${a} != ${b}`);
check('H 400×400×13×21 sharp-corner geometry',()=>{const r=compute(defaults);near(r.A,214.54);near(r.Ix,65361.58713333334);near(r.Iy,22406.55438333333);near(r.ratio,0.6797843806611737);assert.equal(r.status,'pass')});
check('Zero demand is valid and gives zero ratio',()=>near(compute({...defaults,N:0,Mx:0,My:0}).ratio,0));
check('Pure compression capacity equals unity demand',()=>{const a=compute({...defaults,Mx:0,My:0});const r=compute({...defaults,N:a.Pa,Mx:0,My:0});near(r.ratio,1);assert.equal(r.status,'pass')});
check('Compression beyond capacity fails',()=>{const a=compute(defaults);assert.equal(compute({...defaults,N:a.Pa*1.01,Mx:0,My:0}).status,'fail')});
check('Bending signs cannot cancel demand',()=>{const r=compute(defaults),s=compute({...defaults,Mx:-10,My:-2});near(r.ratio,s.ratio)});
check('A longer weak-axis unsupported length decreases capacity',()=>{assert.ok(compute({...defaults,Ly:1000}).Pa<compute(defaults).Pa)});
check('ASD general curve continuous at Cc',()=>{const C=Math.sqrt(2*Math.PI**2*2040000/2400);near(allowable(C-1e-7,2400,2040000),allowable(C+1e-7,2400,2040000),.00001)});
check('Euler branch numeric reference',()=>near(allowable(200,2400,2040000),262.6172997159429,.000001));
check('Welded box uses distinct 6.7 compression curve',()=>{const a=compute({...defaults,shape:'BOX',tf:1.6,Mx:0,My:0});near(a.A,245.76);near(a.Fa,1336.4104012019577);assert.equal(a.status,'pass')});
check('Pipe inertias equal and not subject to box Lc',()=>{const a=compute({...defaults,shape:'PIPE',d:40.64,tf:1.27,N:50,Mx:1});near(a.Ix,a.Iy);assert.equal(a.Lcx,null);assert.equal(a.status,'pass')});
check('Slender pipe must not be approved in compression',()=>{const a=compute({...defaults,shape:'PIPE',d:100,tf:1,N:1,Mx:0,My:0});assert.equal(a.status,'pending')});
check('Pure bending pipe does not expose invalid pure compression capacity',()=>{const a=compute({...defaults,shape:'PIPE',d:100,tf:1,N:0,Mx:1,My:0});assert.equal(a.valid,true);assert.equal(a.axialCapacityValid,false)});
check('Thin H web cannot silently retain gross-section axial capacity',()=>assert.equal(compute({...defaults,tw:.3}).status,'pending'));
check('Welded kc uses division and is below one',()=>{const a=compute({...defaults,fabrication:'welded',d:100,tw:1,N:0,Mx:1,My:0});assert.ok(a.kc>0&&a.kc<1);near(a.kc,4.05/95.8**.46)});
check('Nonpositive amplification denominator yields failure',()=>{const a=compute({...defaults,N:2000,My:20});assert.equal(a.amplified,Infinity);assert.equal(a.status,'fail')});
check('Zero moments avoid 0/negative amplification artefacts',()=>{const a=compute({...defaults,N:2000,My:0,Mx:0});assert.ok(Number.isFinite(a.interaction));assert.equal(a.status,'fail')});
check('Slenderness >200 prevents a pass even at zero demand',()=>assert.equal(compute({...defaults,Ly:3000,N:0,Mx:0,My:0}).status,'fail'));
check('Long unbraced bending reduces strong-axis stress limit',()=>assert.ok(compute({...defaults,Lb:2000}).fbx<compute(defaults).fbx));
check('Invalid inputs never retain a result',()=>{for(const v of [{d:1},{tf:0},{Kx:0},{N:-1},{Fy:NaN},{Mx:Infinity},{Cmx:1.1},{d:1e200}])assert.ok(compute({...defaults,...v}).errors.length)});
check('Box axes swap preserves capacity with moments swapped',()=>{const a=compute({...defaults,shape:'BOX',b:35,d:50,tf:1.6,Lx:400,Ly:500,Mx:8,My:2});const b=compute({...defaults,shape:'BOX',b:50,d:35,tf:1.6,Lx:500,Ly:400,Mx:2,My:8});near(a.ratio,b.ratio)});
console.log(`${count} engineering checks passed`);
